Frontend:
    bash commands /frontend.sh
Redis:
    bash commands /Redis.sh
rabbitmq:
    bash commands /rabbitmq.sh
mongodb:
    bash commands /mongodb.sh
mysql:
    bash commands /mysql.sh
catalogue:
    bash commands /catalogue.sh
cart:
    bash commands /cart.sh
shipping:
    bash commands /shipping.sh
user:
    bash commands /user.sh
