Frontend:
    @bash components/frontend.sh
Redis:
    @bash components/Redis.sh
rabbitmq:
    @bash components/rabbitmq.sh
mongodb:
    @bash components/mongodb.sh
mysql:
    @bash components/mysql.sh
catalogue:
    @bash components/catalogue.sh
cart:
    @bash components/cart.sh
shipping:
    @bash components/shipping.sh
user:
    @bash components/user.sh
